# Generated by Django 5.0.14 on 2026-04-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('style', models.CharField(blank=True, max_length=100, verbose_name='Стиль')),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Арт-промпт',
                'verbose_name_plural': 'Арт-промпты',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='artprompt_a_time_cr_9f749a_idx')],
            },
        ),
    ]
