# Generated by Django 4.2.1 on 2026-04-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artprompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='PromptMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Сложность')),
                ('estimated_time', models.IntegerField(default=30, verbose_name='Время выполнения, мин')),
            ],
        ),
        migrations.CreateModel(
            name='TagPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AddField(
            model_name='artprompt',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='artprompt.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='artprompt',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt', to='artprompt.promptmeta', verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='artprompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='artprompt.tagprompt', verbose_name='Теги'),
        ),
    ]
