# Generated by Django 4.2.1 on 2026-05-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artprompt', '0002_category_promptmeta_tagprompt_artprompt_cat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='promptmeta',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterModelOptions(
            name='tagprompt',
            options={'ordering': ['tag'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveIndex(
            model_name='artprompt',
            name='artprompt_a_time_cr_9f749a_idx',
        ),
        migrations.AddField(
            model_name='promptmeta',
            name='materials',
            field=models.CharField(blank=True, max_length=255, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='promptmeta',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='promptmeta',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Примерное время выполнения, мин.'),
        ),
    ]
