# Generated by Django 4.2.1 on 2026-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artprompt', '0003_alter_category_options_alter_promptmeta_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model/%Y/%m/%d/', verbose_name='Файл')),
                ('time_upload', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.AddField(
            model_name='artprompt',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
