# Generated by Django 4.2.1 on 2026-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artprompt', '0004_uploadedfile_artprompt_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptmeta',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='promptmeta',
            name='materials',
        ),
        migrations.AddField(
            model_name='promptmeta',
            name='style',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стиль'),
        ),
    ]
