# Generated by Django 4.2.1 on 2026-06-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artprompt', '0005_remove_promptmeta_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artprompt',
            options={'ordering': ['-time_create'], 'permissions': [('can_publish_prompt', 'Может публиковать арт-промпты')], 'verbose_name': 'Арт-промпт', 'verbose_name_plural': 'Арт-промпты'},
        ),
    ]
